# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/login_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_Form(object):
    def setupUi(self, login_Form):
        login_Form.setObjectName("login_Form")
        login_Form.resize(1149, 745)
        self.gridLayout_3 = QtWidgets.QGridLayout(login_Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(263, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(login_Form)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    width: 550px;\n"
"    height: 650px;\n"
"    border-radius: 8px;\n"
"    background:rgba(255, 255, 255, 50) ;\n"
"    box-shadow: 2px 2px 10px 1px #63636340;\n"
"    padding:1% 1% 10% 10%;\n"
"    position: static;\n"
"    margin-top: 8%;\n"
"    animation: _ngcontent-gyf-c3_container .7s linear 1 normal;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    font-size: 18px;\n"
"    padding: 10px 10px 10px 5px;\n"
"    display: block;\n"
"    width: 100%;\n"
"    border: none;\n"
"    border-bottom: 1px solid #757575;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"font-weight: 400;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 6, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem4, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 221, 47,0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 0, 1, 1)
        self.login_btn = QtWidgets.QPushButton(self.groupBox)
        self.login_btn.setStyleSheet("QPushButton {\n"
"\n"
"width: 374px;\n"
"height: 41px;\n"
"border-radius: 5px;\n"
"background : #00aced;\n"
"color: #FFF;\n"
"font-size: 16px;\n"
"font-weight: 700;\n"
"\n"
"}")
        self.login_btn.setObjectName("login_btn")
        self.gridLayout.addWidget(self.login_btn, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"color: #999;\n"
"    text-align: center;\n"
"    font-size: 13px;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    text-decoration: underline;\n"
"    border-color : transparent;\n"
"    border:0 ;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"};")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 5, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.username_lin = QtWidgets.QLineEdit(self.groupBox)
        self.username_lin.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.username_lin.setFont(font)
        self.username_lin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.username_lin.setStyleSheet("")
        self.username_lin.setInputMask("")
        self.username_lin.setText("")
        self.username_lin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.username_lin.setObjectName("username_lin")
        self.verticalLayout.addWidget(self.username_lin)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem8)
        self.password_lin = QtWidgets.QLineEdit(self.groupBox)
        self.password_lin.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.password_lin.setFont(font)
        self.password_lin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.password_lin.setStyleSheet("")
        self.password_lin.setInputMask("")
        self.password_lin.setText("")
        self.password_lin.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password_lin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.password_lin.setObjectName("password_lin")
        self.verticalLayout.addWidget(self.password_lin)
        self.gridLayout_2.addLayout(self.verticalLayout, 3, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_2.addItem(spacerItem9, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 1, 2, 2)
        spacerItem10 = QtWidgets.QSpacerItem(263, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 2, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 3, 2, 1, 1)

        self.retranslateUi(login_Form)
        QtCore.QMetaObject.connectSlotsByName(login_Form)

    def retranslateUi(self, login_Form):
        _translate = QtCore.QCoreApplication.translate
        login_Form.setWindowTitle(_translate("login_Form", "Form"))
        self.label_2.setText(_translate("login_Form", "<html><head/><body><p><span style=\" font-size:36pt;\">Sign in to </span><span style=\" font-size:36pt; font-weight:600; color:#14a5ec;\">TwiScope</span></p></body></html>"))
        self.login_btn.setText(_translate("login_Form", "Login"))
        self.pushButton_2.setText(_translate("login_Form", "Forget username / password ?"))
        self.username_lin.setPlaceholderText(_translate("login_Form", "Username / Email"))
        self.password_lin.setPlaceholderText(_translate("login_Form", "Password"))
import app_resources_rc
